### ISSUE TITLE
caffe2 installs Python library to wrong location relative to CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by ezyang** [facebookarchive/caffe2#1015]
I set CMAKE_INSTALL_PREFIX=$PREFIX and caffe2 dumped the Python modules in $PREFIX and not in $PREFIX/lib/python2.7 (or perhaps site-packages) where they should be placed. Subsequently, I had to add $PREFIX to my $PYTHONPATH to get caffe2 to find it.

This was tested on ae9af51496a4485437cf704bc7566eebe5e7f4d6

I used this conda build.sh and meta.yaml to do the build:

```
#!/bin/bash
set -e
if [ -z "$CONDA_CUDA_HOME" ]; then
  CUDA_ARGS=""
else
  CUDA_ARGS="-DCUDA_TOOLKIT_ROOT_DIR=$(printf %q "$CONDA_CUDA_HOME")"
fi
if [ -z "$PREFIX" ]; then
  PREFIX="$CONDA_PREFIX"
fi
rm -rf build || true
PYTHON_ARGS="$(python ./scripts/get_python_cmake_flags.py)"
mkdir -p build
cd build
cmake3 -DCMAKE_INSTALL_PREFIX="$PREFIX" $CUDA_ARGS $PYTHON_ARGS ..
make -j20
make install/fast
```

and

```
{% set version = "0.8.dev" %}

package:
  name: caffe2
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - future
    - glog
    - numpy
    - six
    - eigen
    - python <3
  run:
#   - future
#   - glog
#   - numpy
#   - six
#   - eigen
#   - python ==2.*

about:
  home: https://caffe2.ai/
  license: BSD
  summary: deep learning library

extra:
  recipe-maintainers:
    - ezyang
```
